name: Documentation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - name: Install dev dependencies
        run: julia --project -e 'using Pkg; Beforerr = PackageSpec(url="https://github.com/Beforerr/beforerr.jl"); PlasmaFormulary = PackageSpec(url="https://github.com/Beforerr/PlasmaFormulary.jl")'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
